### ISSUE TITLE
opengate tests not running in WSL2

### ISSUE THREAD

**Issue by BishopWolf** [OpenGATE/opengate#147]
In WSL2, opengate installs successfully. However, when attempting to run opengate-tests : 
```
ubuntu@F-P-Phys-02:~$ opengate_tests
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/opengate_tests", line 7, in <module>
    from opengate.helpers import *
  File "/home/ubuntu/.local/lib/python3.10/site-packages/opengate/__init__.py", line 6, in <module>
    from .geometry.VolumeManager import __world_name__
  File "/home/ubuntu/.local/lib/python3.10/site-packages/opengate/geometry/VolumeManager.py", line 3, in <module>
    import opengate_core as g4
  File "/home/ubuntu/.local/lib/python3.10/site-packages/opengate_core/__init__.py", line 62, in <module>
    from .opengate_core import *
ImportError: libICE.so.6: cannot open shared object file: No such file or directory
```

**Comment by jalexanderl1017** [comment]
I had a similar ImportError message. Have you been able to resolve the issue?

**Comment by jizhang02** [comment]
I also use WSL2, you have to add some sentences to the system path to import .so files. 
Detailed guidance is here. https://opengate-python.readthedocs.io/en/latest/user_guide.html
