### ISSUE TITLE
testing failed

### ISSUE THREAD

**Issue by jizhang02** [OpenGATE/opengate#79]
Hello,
After I installed the opengate, I test the program by running the sentence :
`opengate_tests`
However, there is a error like below, does someone know how to solve it?
```Traceback (most recent call last):
  File "/home/barbara/anaconda3/envs/mc/bin/opengate_tests", line 8, in <module>
    from opengate.helpers import *

  File "/home/barbara/anaconda3/envs/mc/lib/python3.8/site-packages/opengate/__init__.py", line 7, in <module>
    from .geometry.VolumeManager import __world_name__

  File "/home/barbara/anaconda3/envs/mc/lib/python3.8/site-packages/opengate/geometry/VolumeManager.py", line 3, in <module>
    import opengate_core as g4

  File "/home/barbara/anaconda3/envs/mc/lib/python3.8/site-packages/opengate_core/__init__.py", line 68, in <module>
    check_tests_data_folder()

  File "/home/barbara/anaconda3/envs/mc/lib/python3.8/site-packages/opengate_core/testsDataSetup.py", line 21, in check_tests_data_folder
    folderGit = git.Repo(dataLocation)

  File "/home/barbara/anaconda3/envs/mc/lib/python3.8/site-packages/git/repo/base.py", line 266, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir

  File "/home/barbara/anaconda3/envs/mc/lib/python3.8/site-packages/git/repo/base.py", line 347, in common_dir
    raise InvalidGitRepositoryError()

git.exc.InvalidGitRepositoryError
```

**Comment by jizhang02** [comment]
> Hello,
> 
> How do you install opengate. Did you clone the repository with --recurse-submodules option?

No, I didn't clone the repository. 
I just create a new virtual conda environment and install the opengate as the `readme` file says.
Could you please give a detailed sentence? Say, after which step I should clone the repo. Thank you!

**Comment by jizhang02** [comment]
> 
Hello again, if I understand correctly, I need to clone the repo,
When I cloned the repo, it requires username and password.

```
(mc) barbara@rv64:~$ git clone https://gitlab.in2p3.fr/opengate/tests_data
Cloning into 'tests_data'...
Username for 'https://gitlab.in2p3.fr': shibboleth
Password for 'https://shibboleth@gitlab.in2p3.fr': 
```
Is that right?
Thanks

**Comment by dsarrut** [comment]
Hi, 

not really ;) 

indeed, if you want to use gate (and not to develop), you don't need to git clone, only "`pip install opengate`" should work. This is written here: https://opengate-python.readthedocs.io/en/latest/user_guide.html#installation

If this is what you did before reporting the error, it is probably an error from our side, we will investigate and let you know ;)

(Please, note it is still "work in progress", the first beta release is planned in a few months.)

**Comment by jizhang02** [comment]
Ok , understood. Thanks a lot!

**Comment by tbaudier** [comment]
Hi,

Is it possible for you to uninstall opengate and install it again please? :
```
pip uninstall opengate opengate_core
#You should probably run the two commented following lines, change the path:
#rm -rf  <path to python lib>/lib/python3.9/site-packages/opengate_core-0.6.0.dist-info/
#rm -rf <path to python lib>/lib/python3.9/site-packages/opengate_core/
pip install --no-cache-dir --force-reinstall opengate
opengate_tests
```

**Comment by tbaudier** [comment]
Thank you very much.

The main error line is:
```
  cmdline: git clone https://gitlab.in2p3.fr/opengamgate/gam_tests_data.git /home/jing/anaconda3/envs/mc/lib/python3.8/site-packages/opengate_core/../opengate/tests/data
  stderr: 'Cloning into '/home/jing/anaconda3/envs/mc/lib/python3.8/site-packages/opengate_core/../opengate/tests/data'...
fatal: unable to access 'https://gitlab.in2p3.fr/opengamgate/gam_tests_data.git/': server certificate verification failed. CAfile: none CRLfile: none'
```

I cannot reproduce the error on my computer but maybe you can try this (from https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c):

```
pip uninstall opengate opengate_core
#You should probably run the two commented following lines, change the path:
#rm -rf  <path to python lib>/lib/python3.9/site-packages/opengate_core-0.6.0.dist-info/
#rm -rf <path to python lib>/lib/python3.9/site-packages/opengate_core/
export GIT_SSL_NO_VERIFY=1
pip install --no-cache-dir --force-reinstall opengate
opengate_tests
```

**Comment by dsarrut** [comment]
ah, thanks Thomas ! It seems this is due to a certificate, here is the quoted explanation:
> "The basic reason is that your computer doesn't trust the certificate authority that signed the certificate used on the Gitlab server. This doesn't mean the certificate is suspicious, but it could be self-signed or signed by an institution/company that isn't in the list of your OS's list of CAs. What you have to do to circumvent the problem on your computer is telling it to trust that certificate - if you don't have any reason to be suspicious about it." 

We use gitlab hosted by our institution (CNRS) because the data for the tests are large and cannot easily be put on github. It seems that this gitlab certificate may lead to issues, so we will try to see how to solve this. 

In the meantime, please, could you try with the commands indicated by Thomas (`GIT_SSL_NO_VERIFY=1`) and feedback?

**Comment by jizhang02** [comment]
Hi, thank you for point out the problem.
After I put `export GIT_SSL_NO_VERIFY=1`, it still not working. The same error occurs as in the previous log.
Maybe you can downsample the data or crop it a little?

**Comment by tbaudier** [comment]
I do not have a staitforward solution for the moment, sorry.

But you can execute the following lines to be able to get the data tests on your computer:
```
cd /home/jing/anaconda3/envs/mc/lib/python3.8/site-packages/opengate_core/../opengate/tests/
rm -rf data HEAD
wget https://www.creatis.insa-lyon.fr/~baudier/dataOpengateTests.zip
unzip dataOpengateTests.zip

```

**Comment by jizhang02** [comment]
Thank you, Thomas, it is indeed an alternative way to make all tests pass. 👍 👍 👍

**Comment by konhat88** [comment]
For me, this solution did not work. 

To make it work, in file: [pathTo]/.local/lib/python3.10/site-packages/opengate_core/__init__.py
I commented the line "check_tests_data_folder()".

Sorry for commenting to a closed thread.! It may help future users.
